---
title: "Baca Konfigurasi & Raw Data"
output: html_document
---

```{r setup library, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## load library
library(foreign)
library(readxl)
library(XLConnect)
library(data.table)
```

```{r set parameter, include=FALSE, echo=FALSE}
## subject pengolahan data
## tpb -> pengolahan untuk publikasi Indikator TPB
vg_subject = "tpb"

## tahun data yang diolah
vg_tahundata = "2017"

# direktori dan nama rawdata yang akan dipakai
switch(
   vg_tahundata,
   
   ## lokasi rawdata 2015
   "2015" = {
      path_ssn_ind = "E:/R-Programming/BelajaR/tpb/data/SSN201503_KORIND.SAV"
      path_ssn_rt = "E:/R-Programming/BelajaR/tpb/data/SSN201503_KORRT.SAV"
   },
   
   ## lokasi rawdata 2016
   "2016" = {
      path_ssn_ind = "E:/R-Programming/BelajaR/tpb/data/SSN201603_KORIND.SAV"
      path_ssn_rt = "E:/R-Programming/BelajaR/tpb/data/SSN201603_KORRT.SAV"
   },
   
   ## lokasi rawdata 2017
   "2017" = {
      path_ssn_ind = "E:/R-Programming/BelajaR/tpb/data/SSN201703_KORIND.SAV"
      path_ssn_rt = "E:/R-Programming/BelajaR/tpb/data/SSN201703_KORRT.SAV"
   }
)
```

```{r config by parameter, include=FALSE, echo=FALSE}
dir = vg_subject
dir_root = getwd()
dir_root = substr(dir_root, 1, nchar(dir_root) - nchar(dir) - 1)
dir_hasil = paste(dir_root, dir, "hasil", sep = "/")
dir_data = paste(dir_root, dir, "data",vg_tahundata, sep = "/")
```

```{r read matriks variable, include=FALSE, echo=FALSE}
## lokasi file excel yang berisi matrik variable susenas dan pemrograman R
path_varSSN = paste(dir_root, "_include/varssn.xls", sep = "/")
wb_var = loadWorkbook(path_varSSN)

## baca matrik variabel R-SSN Individu
if (file.exists(path_varSSN) & existsSheet(wb_var, "individu")) {
   var_ssnIND = read_xls(path_varSSN, sheet = "individu")
   
## translasi variabel kuesioner susenas ke variable R
   varSSN = paste("V", vg_tahundata, sep = "")
   for (var_r in var_ssnIND$R) {
      assign(var_r, var_ssnIND[[varSSN]][which(var_ssnIND$R == var_r)])
   }
} else print("file atau sheet tidak ada")

## baca matrik variabel R-SSN Rumah Tangga
if (file.exists(path_varSSN) & existsSheet(wb_var, "rumahtangga")) {
   var_ssnRT = read_xls(path_varSSN, sheet = "rumahtangga")
   
   ## translasi variabel kuesioner susenas ke variable R
   varSSN = paste("V", vg_tahundata, sep = "")
   for (var_r in var_ssnRT$R) {
      assign(var_r, var_ssnRT[[varSSN]][which(var_ssnRT$R == var_r)])
   }
} else print("file atau sheet tidak ada")

## hapus wb_var
rm(wb_var)
```

```{r read rawdata, include=FALSE, echo=FALSE}
#path_ssnIND = path_raw[match(paste("ssnind", vg_tahundata, sep = "_"), path_raw) + 1]
#path_ssnRT = path_raw[match(paste("ssnrt", vg_tahundata, sep = "_"), path_raw) + 1]

if (file.exists(path_ssn_ind)) {
   dt_ssnIND = setDT(read.spss(path_ssn_ind))
} else print("file tidak ada")

if (file.exists(path_ssn_rt)) {
   dt_ssnRT = setDT(read.spss(path_ssn_rt))
} else print("file tidak ada")

```


