---
title: "Tujuan 01"
output: html_document
---

```{r setup & library, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# load library
library(foreign)
library(data.table)
#library(Hmisc)
library(XLConnect)
library(grattan)

tujuan = "tujuan01"
```

```{r Beberapa function bantuan, echo=FALSE, include=FALSE}
## fungsi untuk mengecek air minum dengan kombinasi
## air mandi yang digunakan
cek_mandi = function(minum, mandi) {
   result = mandi %in% ar_mandi[!ar_mandi %in% minum]
   return(result)
}
```


### Penggolongan Kuantil
```{r Penggolongan Kuantil Data Individu, include=FALSE, echo=FALSE}
## set index variabel akan sering dipakai
setkeyv(dt_ssnIND, c(prov, kota_desa, jenis_kel, expcap))

## Kuantil Nasional
dt_ssnIND[,
   ## variable baru kuantil Nasional
   QNas:= weighted_ntile(get(expcap), get(bobot), n=5)
]

## Kuantil Kota - Desa
dt_ssnIND[,
   QKD:= weighted_ntile(get(expcap), get(bobot), n=5),
   by = get(kota_desa)
]

## Kuantil Jenis Kelamin
dt_ssnIND[,
   QLP:= weighted_ntile(get(expcap), get(bobot), n=5),
   by = get(jenis_kel)
]

## Kuantil Provinsi
dt_ssnIND[,
   QProv:= weighted_ntile(get(expcap), get(bobot), n=5),
   by = get(prov)
]
```

```{r Penggolongan Kuantil Data Rumah Tangga, include=FALSE, echo=FALSE}
setkeyv(dt_ssnRT, c(prov, kota_desa, expcap))

## Kuantil Nasional
dt_ssnRT[,
   QNas:= weighted_ntile(get(expcap_rt), get(bobot_rt) * get(n_art), n=5)
]

## Kuantil Kota -Desa
dt_ssnRT[,
   QKD:= weighted_ntile(get(expcap_rt), get(bobot_rt) * get(n_art), n=5),
   by = get(kota_desa)
]

## Kuantil Provinsi
dt_ssnRT[,
   QProv:= weighted_ntile(get(expcap_rt), get(bobot_rt) * get(n_art), n=5),
   by = get(prov)
]
```

### Indikator 1.4.1.(a)
```{r Konsep dan Definisi, include=FALSE, echo=FALSE}
# ************************************************************************
# indikator 1.4.1.(a)
# ___________________
# Persentase perempuan pernah kawin umur 15-49 tahun
# yang proses melahirkan terakhirnya di fasilitas kesehatan.
# 
# RUMUS ******************************************************************
#                 JPSalifaskes
# PSalifaskes = ---------------- X 100%
#                  JP15-49th        
#
# Keterangan
# PSalifaskes  = Persentase perempuan pernah kawin umur 15-49 tahun 
#                yang proses melahirkan terakhirnya di fasilitas kesehatan
# JPSalifaskes = Jumlah perempuan pernah kawin umur 15-49 tahun yang 
#                proses melahirkan terakhirnya di fasilitas kesehatan
#                (penduduk 40% terbawah/berpendapatan terendah)
# JP15-49      = Jumlah perempuan pernah kawin umur 15-49 tahun 
#                yang pernah melakukan persalinan
#                (penduduk 40% terbawah/berpendapatan terendah)
#************************************************************************

#JP15-49 ==>   R405 = 2
#              R404 >= 2
#              R407 >= 15 dan R407 <= 49
#              R1301 = 1
#              EXPCAP = kuintil 1 dan kuintil 2

#JPSalifaskes  filter JP15-49 dan
#              R1302A = Rumah Sakit/Rumah Sakit Bersalin, 
#                       Klinik/Bidan/Praktek Dokter
#                       Puskesmas/Pustu/Polindes
```

```{r Pembentukan variable JPSalifaskes, echo=FALSE}
indikator = "1.4.1.(a)"


## define rincian faskes persalinan berdasarkan tahun data
faskes2015 = c("2015", "2016")
if (any(faskes2015 == vg_tahundata)) {
   faskes = c(1,2,3) 
}

faskes2017 = c("2017")
if (any(faskes2017 == vg_tahundata)) {
   faskes = c(1,2,3,4,5,6) 
}

dt_ssnIND[
   ## filter jenis kelamin
   get(jenis_kel) == 2 &
      
   ## filter status pernah kawin
   get(stat_kawin) >= 2 &
      
   ## filter umur 15-19
   get(umur) >= 15 & get(umur) <= 49 &
      
   ## filter pernah melahirkan lahir hidup
   get(lahir_hidup_2th) == 1,
   
   ## variable baru 
   ## penduduk yang melakukan persalinan di Faskes
   JPSalifaskes:= as.integer(get(tempat_salin) %in% faskes) * 100
]
```

```{r Penghitungan angka nasional, include=FALSE, echo=FALSE}
## Persentase Nasional
hasil = dt_ssnIND[
   ## filter kuintil nasional
   QNas <= 2,
   
   ## Persentase Nasional
   .(PNas =  weighted.mean(JPSalifaskes, get(bobot), na.rm = TRUE))
]

## simpan hasil di excel
write2xl(hasil$PNas, "nasional")

## Persentase Kota Desa
hasil = dt_ssnIND[
   ## filter kuintil Kota Desa
   QKD <= 2,
   
   ## Persentase Kota Desa
   .(PKD = weighted.mean(JPSalifaskes, get(bobot), na.rm = TRUE)),
   
   ## group by kota desa
   by = kota_desa
]

## simpan hasil di excel
write2xl(unlist(c(hasil[1,2], hasil[2,2])), "kotadesa")
```

```{r Penghitungan angka provinsi, echo=FALSE, include=FALSE}
## Penghitungan Perentase Provinsi
hasil = dt_ssnIND[
   ## filter kuintil Provinsi, 1 dan 2
   QProv <= 2,
   
   ## Persentase Provinsi
   .(PProv = weighted.mean(JPSalifaskes, get(bobot), na.rm = TRUE)),
   
   ## agregasi Provinsi
   by = prov
]

## simpan hasil di excel
write2xl(hasil$PProv, "provinsi")
```


### Indikator 1.4.1.(b)
```{r Konsep dan Definisi, include=FALSE, echo=FALSE}
# ************************************************************************
# indikator 1.4.1.(b)
# ___________________
# Persentase anak umur 12-23 bulan yang menerima imunisasi dasar lengkap
#
# RUMUS ******************************************************************
#             JAIDL
# PIDL = ---------------- X 100%
#           JA12-23bln        
#
# Keterangan
# PIDL         = Persentase anak umur 12-23 bulan 
#                yang menerima imunisasi dasar lengkap
# JAIDL        = Banyaknya anak umur 12-23 bulan 
#                yang telah menerima imunisasi dasar lengkap 
#                pada periode waktu tertentu
#                (penduduk 40% terbawah/berpendapatan terendah)
# JA12-23bln   = Jumlah anak umur 12-23 bulan pada periode waktu yang sama
#                (penduduk 40% terbawah/berpendapatan terendah)
#************************************************************************

#JA12-23bln ==>   R902 >= 12 & R902 <= 23
#                 pendapatan 40% terendah

#JAIDL      ==>   filter JA12-23bln dan
#                 3x DPT 3x Polio 1x Campak 1x BCG 3x Hepatitis B
```

```{r Pembentukan variable Imunisasi Dasar Lengkap, echo=FALSE, include=FALSE}
indikator = "1.4.1.(b)"

# define minimal jumlah imunisasi
nDPT = 3
nPolio = 3
nCampak = 1
nBCG = 1
nHB = 3

## define imunisasi berdasarkan tahun survey
switch(
   vg_tahundata,
   
   "2015" = {
      ## rincian2 imunisasi DPT
      ##ar_DPT = c(r902f, r902g, r902h)
   },
   
   "2016" = {
      ## rincian semua imunisasi
      ar_imun = c(imun_bcg, imun_polio1, imun_polio2, imun_polio3, imun_polio4,
                  imun_dpt1, imun_dpt2, imun_dpt3, imun_hb_lahir, imun_hb1,
                  imun_hb2, imun_hb3, imun_campak)
      
      ar_bcg = c(imun_bcg)
      
      ar_polio = c(imun_polio1, imun_polio2, imun_polio3, imun_polio4)
      
      ar_dpt = c(imun_dpt1, imun_dpt2, imun_dpt3)
      
      ar_hb = c(imun_hb_lahir, imun_hb1, imun_hb2, imun_hb3)
      
      ar_campak = c(imun_campak)
   },
   
   "2017" = {
      ## rincian semua imunisasi
      ar_imun = c(imun_bcg, imun_polio1, imun_polio2, imun_polio3, imun_polio4,
                  imun_dpt1, imun_dpt2, imun_dpt3, imun_hb_lahir, imun_hb1,
                  imun_hb2, imun_hb3, imun_campak)
       
       
      ar_imun = c("r1104a_tgl", "r1104b_tgl", "r1104c_tgl", "r1104d_tgl", "r1104e_tgl",
                  "r1104f_tgl", "r1104g_tgl", "r1104h_tgl", "r1104i_tgl", "r1104j_tgl",
                  "r1104k_tgl", "r1104l_tgl", "r1104m_tgl", "r1104n_tgl")
      
      # clean data
      ## replace data tanggal imunisasi ke 1 bila tanggal > 0
      for (j in names(dt_ssnIND[, ar_imun, with = FALSE])) {
         set(dt_ssnIND,which(dt_ssnIND[[j]] > 0),j,1)
      }
   }
)

## cleaning data, replace NA value to 0
for (j in names(dt_ssnIND[, ar_imun, with = FALSE])) {
   set(dt_ssnIND,which(is.na(dt_ssnIND[[j]])),j,0)
}

## penghitungan jumlah imunisasi berdasarkan
## catatan kartu KMS
dt_ssnIND[,
   
   `:=` (
      ## total imunisasi BCG
      kbcg = rowSums(dt_ssnIND[, ar_bcg, with=FALSE], na.rm = TRUE),
      
      ## total imunisasi Polio
      kpolio = rowSums(dt_ssnIND[, ar_polio, with=FALSE], na.rm = TRUE),
      
      ## total imunisasi DPT
      kdpt = rowSums(dt_ssnIND[, ar_dpt, with=FALSE], na.rm = TRUE),
      
      ## total imunisasi Hepatitis B
      khb = rowSums(dt_ssnIND[, ar_hb, with=FALSE], na.rm = TRUE),
      
      ## total imunisasi Campak
      kcampak = rowSums(dt_ssnIND[, ar_campak, with=FALSE], na.rm = TRUE)
   )
]

## penghitungan jumlah imunisasi berdasarkan
## ingatan responden
dt_ssnIND[,
   `:=` (
      ## imunisasi bcg berdasarkan ingatan responden
      mbcg = ifelse(get(bcg_cek) == 1, 1,0),
      
      ## imunisasi campak berdasarkan ingatan responden
      mcampak = ifelse(get(campak_cek) == 1, 1,0)
   )
]

dt_ssnIND[
   ## responden tidak dapat menunjukkan kartu KMS
   get(kartu_kms) == 2 | get(punya_kms) > 0,
   
   `:=` (
      ## imunisasi polio berdasarkan ingatan responden
      mpolio = get(polio_cek),
      
      ## imunisasi dpt berdasarkan ingatan responden
      mdpt = get(dpt_cek),
      
      ## imunisasi hepatitis B berdasarkan ingatan responden
      mhb = get(hb_cek)
   )
]

ar_na2 = c("kbcg", "kpolio", "kdpt", "khb", "kcampak", 
           "mbcg", "mpolio", "mdpt", "mhb", "mcampak")
## cleaning data, replace NA value to 0
for (j in names(dt_ssnIND[, ar_na2, with = FALSE])) {
   set(dt_ssnIND,which(is.na(dt_ssnIND[[j]])),j,0)
}

## definisi imunisasi dasar lengkap 
## dengan menjumlah hasil 2 metode diatas
dt_ssnIND[,
   ## variable imunisasi dasar lengkap
   IDL:= as.integer(
      ## cek jumlah imunisasi BCG
      (kbcg + mbcg) >= nBCG &
      
      ## cek jumlah imunisasi Polio
      (kpolio + mpolio) >= nPolio &
      
      ## cek jumlah imunisasi DPT
      (kdpt + mdpt) >= nDPT &
   
      ## cek jumlah imunisasi Hepatitis B
      (khb + mhb) >= nHB &
         
      ## cek jumlah imunisasi Campak
      (kcampak + mcampak) >= nCampak
   )
]
```

```{r Penghitungan angka nasional, include=FALSE, echo=FALSE}
## Persentase Nasional
hasil = dt_ssnIND[
   ## filter umur balita 12-23 bulan
   get(umur_balita) >= 12 & get(umur_balita) <= 23 &
   
   ## filter kuintil nasional
   QNas <= 2,
   
   ## Persentase Nasional
   .(PNas =  weighted.mean(IDL, get(bobot), na.rm = TRUE) * 100)
]

## simpan hasil di excel
write2xl(hasil$PNas, "nasional")

## Persentase Laki-Perempuan
hasil = dt_ssnIND[
   ## filter umur balita 12-23 bulan
   get(umur_balita) >= 12 & get(umur_balita) <= 23 &
   
   ## filter kuintil Kota Desa
   QLP <= 2,
   
   ## Persentase Kota Desa
   .(PLP = weighted.mean(IDL, get(bobot), na.rm = TRUE) * 100),
   
   ## group by kota desa
   by = jenis_kel
]

## simpan hasil di excel
write2xl(unlist(c(hasil[1,2], hasil[2,2])), "jk")

## Persentase Kota Desa
hasil = dt_ssnIND[
   ## filter umur balita 12-23 bulan
   get(umur_balita) >= 12 & get(umur_balita) <= 23 &
   
   ## filter kuintil Kota Desa
   QKD <= 2,
   
   ## Persentase Kota Desa
   .(PKD = weighted.mean(IDL, get(bobot), na.rm = TRUE) * 100),
   
   ## group by kota desa
   by = kota_desa
]

## simpan hasil di excel
write2xl(unlist(c(hasil[1,2], hasil[2,2])), "kotadesa")
```

```{r Penghitungan angka provinsi, echo=FALSE, include=FALSE}
## Penghitungan Perentase Provinsi
hasil = dt_ssnIND[
   ## filter umur balita 12-23 bulan
   get(umur_balita) >= 12 & get(umur_balita) <= 23 &
      
   ## filter kuintil Provinsi, 1 dan 2
   QProv <= 2,
   
   ## Persentase Provinsi
   .(PProv = weighted.mean(IDL, get(bobot), na.rm = TRUE) * 100),
   
   ## agregasi Provinsi
   by = prov
]

## simpan hasil di excel
write2xl(hasil$PProv, "provinsi")
```

## Indikator 1.4.1.(c)
```{r Konsep dan Definisi, echo=FALSE, include=FALSE}
# ************************************************************************
# indikator 1.4.1.(c)
# ___________________
# Prevalensi penggunaan metode kontrasepsi (CPR) semua cara 
# pada Pasangan Usia Subur (PUS) usia 15-49 tahun yang berstatus kawin
#
# RUMUS ******************************************************************
#              JPUS-CPRSC
# CPR-SC = ------------------ X 100%
#              JPUS15-49        
#
# Keterangan
# CPR-SC       = Pemakaian kontrasepsi (CPR) semua cara 
#                pada Pasangan Usia Subur (PUS) umur15-49 tahun
#                yang berstatus kawin
# JPUS-CPRCS   = Jumlah PUS umur 15-49 tahun peserta KB aktif
#                yang menggunakan alat kontrasepsi semua
#                cara pada periode waktu tertentu 
#                (penduduk 40% terbawah/berpendapatan terendah)
# JPUS15-49    = Jumlah PUS umur 15-49 tahun pada periode waktu yang sama 
#                (penduduk 40% terbawah/berpendapatan terendah)
#************************************************************************

#JPUS15-49  ==>   R407 >= 15 & R407 <= 49
#                 R404 = 2
#                 R405 = 2
#                 pendapatan 40% terendah

#JPUS-CPRCS ==>   filter JPUS15-49 dan
#                 R1401 = 2
```

```{r Pembentukan variable JPUS-CPRCS, echo=FALSE}
indikator = "1.4.1.(c)"

dt_ssnIND[
   ## filter umur 15-49thn
   get(umur) >= 15 & get(umur) <= 49 &
      
   ## jenis kelamin perempuan
   get(jenis_kel) == 2 &
      
   ## status perkawinan = kawin
   get(stat_kawin) == 2,
   
   ## variale baru
   ## PUS yang menggunakan KB
   PUS_CPRCS:= as.integer(get(kb_pakai) == 2) * 100
]
```

```{r Penghitungan angka nasional, include=FALSE, echo=FALSE}
## Persentase Nasional
hasil = dt_ssnIND[
   ## filter kuintil nasional
   QNas <= 2,
   
   ## Persentase Nasional
   .(PNas =  weighted.mean(PUS_CPRCS, get(bobot), na.rm = TRUE))
]

## simpan hasil di excel
write2xl(hasil$PNas, "nasional")

## Persentase Kota Desa
hasil = dt_ssnIND[
   ## filter kuintil Kota Desa
   QKD <= 2,
   
   ## Persentase Kota Desa
   .(PKD = weighted.mean(PUS_CPRCS, get(bobot), na.rm = TRUE)),
   
   ## group by kota desa
   by = kota_desa
]

## simpan hasil di excel
write2xl(unlist(c(hasil[1,2], hasil[2,2])), "kotadesa")
```

```{r Penghitungan angka provinsi, echo=FALSE, include=FALSE}
## Penghitungan Perentase Provinsi
hasil = dt_ssnIND[
   ## filter kuintil Provinsi, 1 dan 2
   QProv <= 2,
   
   ## Persentase Provinsi
   .(PProv = weighted.mean(PUS_CPRCS, get(bobot), na.rm = TRUE)),
   
   ## agregasi Provinsi
   by = prov
]

## simpan hasil di excel
write2xl(hasil$PProv, "provinsi")
```

## Indikator 1.4.1.(d)
```{r Konsep dan Definsi, echo=FALSE, include=FALSE}
# ************************************************************************
# indikator 1.4.1.(d)
# ___________________
# Persentase rumah tangga yang memiliki akses terhadap layanan sumber
# air minum layak dan berkelanjutan
#
# RUMUS ******************************************************************
#              JRTML
# PAML = ------------------ X 100%
#              JRTS        
#
# Keterangan
# PAML         = Persentase rumah tangga yang memiliki akses
#                terhadap layanan sumber air minum layak dan
#                berkelanjutan
# JRTML        = Jumlah rumah tangga dengan akses terhadap
#                sumber air minum berkualitas (layak)
# JRTS         = Jumlah rumah tangga seluruhnya
#                (penduduk 40% terbawah/berpendapatan terendah)
#************************************************************************

# JRTS      ==>   pendapatan 40% terendah

# Rumah Tangga
# Air Layak ==>   Rumah tangga dikatakan menggunakan/mempunyai akses air minum layak 
#                 apabila sumber air minum yang digunakan rumah tangga berasal dari 
#                 leding, air terlindung (pompa/sumur bor, sumur terlindung, 
#                 mata air terlindung) dengan jarak >= 10 m dari penampungan kotoran/limbah, 
#                 dan air hujan (Rumus 1). 
#                 Dikombinasikan dengan penggunaan air mandi/cuci yang bersumber dari air terlindung 
#                 (leding meteran, leding eceran, sumur bor/pompa, sumur terlindung, 
#                 mata air terlindung, dan air hujan) bila sumber air minum utama menggunakan 
#                 air kemasan/isi ulang dan air tidak terlindungi 
#                 (air terlindungi dengan jarak < 10 m dan air tidak terlindung)
```

```{r Pembentukan variable Air Minum Layak, echo=FALSE}
indikator = "1.4.1.(d)"

## define rincian untuk filter air minum layak
switch(
   vg_tahundata,
   
   "2015" = {
      ## rincian2 imunisasi DPT
      ##ar_DPT = c(r902f, r902g, r902h)
   },
   
   "2016" = {
      #  rincian air minum terlindungi
      ## Leding meteran, Leding eceran, Air Hujan
      ar_minum = c(3,4,11)
      
      #  rincian air terlindung dengan jarak >= 10m
      ## Sumur bor/pompa, Sumur terlindung, Mata air terlindung
      ar_minum_jarak = c(5,6,8)
      
      #  rincian air minum tidak sustain
      ## Air kemasan bermerk, Air isi ulang
      ar_tdk_sustain = c(1,2)
      
      #  rincian air minum tidak tidak terlindung
      ## Sumur tak terlindung, Mata air tak terlindung, Air Sungai, lainnya
      ar_tdk_terlindung = c(7,9,10,12)
      
      #  rincian air mandi/cuci yan terlindung
      ## Leding meteran, Leding eceran, Sumur bor/pompa, Sumur terlindung
      ## Mata air terlindung, Air Hujan
      ar_mandi = c(3,4,5,6,8,11)
   },
   
   "2017" = {
      #  rincian air minum terlindungi
      ## Leding, Air Hujan
      ar_minum = c(3,10)
      
      #  rincian air terlindung dengan jarak >= 10m
      ## Sumur bor/pompa, Sumur terlindung, Mata air terlindung
      ar_minum_jarak = c(4,5,7)
      
      #  rincian air minum tidak sustain
      ## Air kemasan bermerk, Air isi ulang
      ar_tdk_sustain = c(1,2)
      
      #  rincian air minum tidak tidak terlindung
      ## Sumur tak terlindung, Mata air tak terlindung, Air Sungai, lainnya
      ar_tdk_terlindung = c(6,8,9,11)
      
      #  rincian air mandi/cuci yan terlindung
      ## Leding, Sumur bor/pompa, Sumur terlindung
      ## Mata air terlindung, Air Hujan
      ar_mandi = c(3,4,5,7,10)
   }
)

## define variable baru untuk air minum layak
dt_ssnRT[,
   air_layak:= as.integer(
      ## penghitungan dengan rumus 1
      (
         ## air minum terlindungi
         get(air_minum) %in% ar_minum |
            
         ## air minum terlindungi dengan jarak >= 10m
         (get(air_minum) %in% ar_minum_jarak & get(jarak_air_minum) == 2)
      ) |
      
      ## penghitungan rumus 2
      (
         ## air minum terlindungi dengan jarak < 10m atau tidah tahu
         (
            get(air_minum) %in% ar_minum_jarak & 
            get(jarak_air_minum) != 2 &
            mapply(cek_mandi, get(air_minum), get(air_mandi))
            ## referensi penggunaan mapply di
            ## https://stackoverflow.com/questions/25431307/r-data-table-apply-function-to-rows-using-columns-as-arguments
         ) |
         
         ## air minum tidak sustain dan tidak terlindung
         (
            (get(air_minum) %in% ar_tdk_sustain | get(air_minum) %in% ar_tdk_terlindung) &
            get(air_mandi) %in% ar_mandi
         )
      )
   ) * 100
]
```


```{r Penghitungan angka nasional, include=FALSE, echo=FALSE}
## Persentase Nasional
hasil = dt_ssnRT[
   ## filter kuintil nasional
   QNas <= 2,
   
   ## Persentase Nasional
   .(PNas =  weighted.mean(air_layak, get(bobot_rt), na.rm = TRUE))
]

## simpan hasil di excel
write2xl(hasil$PNas, "nasional")

## Persentase Kota Desa
hasil = dt_ssnRT[
   ## filter kuintil Kota Desa
   QKD <= 2,
   
   ## Persentase Kota Desa
   .(PKD = weighted.mean(air_layak, get(bobot_rt), na.rm = TRUE)),
   
   ## group by kota desa
   by = kota_desa
]

## simpan hasil di excel
write2xl(unlist(c(hasil[1,2], hasil[2,2])), "kotadesa")
```

```{r Penghitungan angka provinsi, echo=FALSE, include=FALSE}
## Penghitungan Perentase Provinsi
hasil = dt_ssnRT[
   ## filter kuintil Provinsi, 1 dan 2
   QProv <= 2,
   
   ## Persentase Provinsi
   .(PProv = weighted.mean(air_layak, get(bobot_rt), na.rm = TRUE)),
   
   ## agregasi Provinsi
   by = prov
]

## simpan hasil di excel
write2xl(hasil$PProv, "provinsi")
```

## Indikator 1.4.1.(e)
```{r Konsep dan Definisi, echo=FALSE, include=FALSE}
# ************************************************************************
# indikator 1.4.1.(e)
# ___________________
# Persentase rumah tangga yang memiliki akses terhadap 
# layanan sanitasi layak dan berkelanjutan
#
# RUMUS ******************************************************************
#              JRTSL
# PLSL = ------------------ X 100%
#              JRTS        
#
# Keterangan
# PLSL         = Persentase rumah tangga yang memiliki akses
#                terhadap layanan sumber air minum layak dan
#                berkelanjutan
# JRTSL        = Jumlah rumah tangga dengan akses terhadap
#                sumber air minum berkualitas (layak)
# JRTS         = Jumlah rumah tangga seluruhnya
#                (penduduk 40% terbawah/berpendapatan terendah)
#************************************************************************

#JRTS       ==>   pendapatan 40% terendah

#JRTSL      ==>   filter JRTS dan
#                 R1507A = 1 atau 2
#                 R1507B = 1 
#                 R1507C = 1 atau 3
```

```{r Nasional; Kota; Desa, echo=FALSE}
indikator = "1.4.1.(e)"

switch(
   vg_tahundata,
   
   "2015" = {
      
   },
   
   "2016" = {
      ar_fasBAB = c(1,2)
      
      ar_kloset = c(1)
      
      ar_tpa = c(1,2,3)
   },
   
   "2017" = {
      
   }
)

dt_ssnRT[,
   ## variable baru Layanan sanitasi layak
   LSL:= as.integer(
      get(fas_bab) %in% ar_fasBAB &
      get(jenis_kloset) %in% ar_kloset &
      get(tpa) %in% ar_tpa
   ) * 100
]
```

```{r Penghitungan angka nasional, include=FALSE, echo=FALSE}
## Persentase Nasional
hasil = dt_ssnRT[
   ## filter kuintil nasional
   QNas <= 2,
   
   ## Persentase Nasional
   .(PNas =  weighted.mean(LSL, get(bobot_rt), na.rm = TRUE))
]

## simpan hasil di excel
write2xl(hasil$PNas, "nasional")

## Persentase Kota Desa
hasil = dt_ssnRT[
   ## filter kuintil Kota Desa
   QKD <= 2,
   
   ## Persentase Kota Desa
   .(PKD = weighted.mean(LSL, get(bobot_rt), na.rm = TRUE)),
   
   ## group by kota desa
   by = kota_desa
]

## simpan hasil di excel
write2xl(unlist(c(hasil[1,2], hasil[2,2])), "kotadesa")
```

```{r Penghitungan angka provinsi, echo=FALSE, include=FALSE}
## Penghitungan Perentase Provinsi
hasil = dt_ssnRT[
   ## filter kuintil Provinsi, 1 dan 2
   QProv <= 2,
   
   ## Persentase Provinsi
   .(PProv = weighted.mean(LSL, get(bobot_rt), na.rm = TRUE)),
   
   ## agregasi Provinsi
   by = prov
]

## simpan hasil di excel
write2xl(hasil$PProv, "provinsi")
```

## Indikator 1.4.1.(f)
```{r Konsep dan Definisi, echo=FALSE, include=FALSE}
# ************************************************************************
# indikator 1.4.1.(f)
# ___________________
# Persentase Persentase rumah tangga kumuh perkotaan
#
# RUMUS ******************************************************************
#              JRTKP
# PRTKP = ---------------- X 100%
#              JRTP        
#
# Keterangan
# PRTKP        = Persentase rumah tangga kumuh perkotaan
# JRTKP        = Jumlah rumah tangga kumuh di perkotaan
#                pada waktu tertentu (penduduk 40% terbawah/
#                berpendapatan terendah)
# JRTP         = Jumlah rumah tangga seluruhnya
#                (penduduk 40% terbawah/berpendapatan terendah)
#************************************************************************

# Daerah kumuh adalah daerah atau kawasan tempat tinggal (hunian) 
# yang dihuni sekelompok orang yang menempati bangunan sementara, 
# tidak ada akses air yang aman untuk diminum, tidak ada
# fasilitas sanitasi yang layak, dan kondisi lingkungan yang tidak memadai. 
# Persentase rumah tangga kumuh adalah perbandingan antara banyaknya
# rumah tangga kumuh dengan jumlah rumah tangga seluruhnya, 
# dinyatakan dalam satuan persen (%).
# Rumah tangga kumuh didefinisikan sebagai rumah tangga yang 
# tidak memiliki akses terhadap sumber air minum layak, sanitasi layak, 
# luas lantai > 7, 2 m2 per kapita, kondisi atap, lantai, 
# dan dinding yang layak. Dihitung dengan menggunakan pembobot
# untuk masing-masing indikator, dikatakan kumuh jika rumah tangga 
# memiliki nilai kategori > 35%.
# Perhitungan indikator ini difokuskan pada penduduk 40% terbawah yaitu 
# tingkat pendapatan rendah (kuintil 1 dan kuintil 2).
```

```{r Pembentukan variable Rumah Kumuh Perkotaan, echo=FALSE, include=FALSE}
indikator = "1.4.1.(f)"


## definisi rincian2 menurut tahun data
switch(
   vg_tahundata,
   
   "2015" = {
      
   },
   
   "2016" = {
      ## rincian jenis bahan atap yang layak
      ar_atap = c(1,2,3,4,5,6,7,8)
      
      ## rincian jenis bahan dinding yang layak
      ar_dinding = c(1,2,3,4)
      
      ## rincian jenis bahan lantai yang layak
      ar_lantai = c(1,2,3,4,5,6,7,8)
      
      
   },
   
   "2017" = {
      ## rincian jenis bahan atap yang layak
      ar_atap = c(1,2,3,4,5,6)
      
      ## rincian jenis bahan dinding yang layak
      ar_dinding = c(1,2,3,4)
      
      ## rincian jenis bahan lantai yang layak
      ar_lantai = c(1,2,3,4,5,6,7)
   }
)

dt_ssnRT[,
   `:=`(
      ## kriteria sanitasi
      ## kebalikan dari sanitasi layak
      Rsani = abs(LSL/100 - 1),
      
      ## kriteria luas lantai
      Rsuff = as.integer((get(luas_lantai) / get(n_art)) <= 7.2),
      
      ## kriteria durability (aladin)
      durab = as.integer(
         ## jika 2 dari 3 kriteria terpenuhi => dianggap kumuh
         (
            ## kriteria atap
            ifelse(get(atap) %in% ar_atap, 0, 1) +
         
            ## kriteria dinding
            ifelse(get(dinding) %in% ar_dinding, 0, 1) + 
         
            ## kriteria lantai
            ifelse(get(lantai) %in% ar_lantai, 0, 1)
         ) >= 2
      ),
      
      ## kriteria air minum
      ## kebalikan dari air minum layak
      Rair = abs(air_layak/100 - 1)
   )
][,
   ## skoring rumah tangga kumuh
   RTKumuh:= ifelse(
     ((Rair * 15) + (Rsani * 15) + (Rsuff * 35) + (durab * 35)) > 35, 100, 0
   ) 
]

dt_ssnRT[
   ## filter kuintil nasional
   QNas <= 2,
   
   ## Persentase Nasional
   .(PNas =  weighted.mean(RTKumuh, get(bobot_rt), na.rm = TRUE))
]
```

